[tool.poetry]
name = "sudoku-solver"
version = "1.0.0"
description = ""
authors = ["Melody Asper <melodieasper@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
